env: "local" # local, dev, stage, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8081"
  timeout: 4s
  #для keep alive
  idle_timeout: 60s
  user: "myuser"
  password: "mypassword"